export const Scc_User_data = [
    { SLNO: '1', status: 'unsafe', PlantName: 'First Manufacturing Division', Name:"Rajesh" },
    { SLNO: '2', status: 'Warning', PlantName: 'Second Manufacturing Division', Name:"Venu"},
    { SLNO: '3', status: 'safe', PlantName: 'Third Manufacturing Division', Name:"Ram"},
    { SLNO: '4', status: 'Warning', PlantName: 'KP Plan of Oil Refinery',Name:"Pavan" },
    { SLNO: '5', status: 'safe', PlantName: 'VP Plant Manufacturing Division',Name:"Kalyan"},
    { SLNO: '6', status: 'Warning', PlantName: 'Fifth Manufacturing Division',Name:"Dhinesh"},
    { SLNO: '7', status: 'safe', PlantName: 'Fifth Manufacturing Division',Name:"Niju"},
    { SLNO: '8', status: 'safe', PlantName: 'KP Plan of Oil Refinery',Name:"Prashanth" },
    { SLNO: '9', status: 'unsafe', PlantName: 'First Manufacturing Division',Name:"Rohith" },
    { SLNO: '10', status: 'Warning', PlantName: 'KP Plan of Oil Refinery',Name:"Rajan"},
    { SLNO: '11', status: 'unsafe', PlantName: 'Third Manufacturing Division',Name:"Ravi"},
    { SLNO: '12', status: 'safe', PlantName: 'Fifth Manufacturing Division',Name:"Niju"},
    { SLNO: '13', status: 'safe', PlantName: 'KP Plan of Oil Refinery',Name:"Prashanth" },
    { SLNO: '14', status: 'unsafe', PlantName: 'First Manufacturing Division',Name:"Rohith" },
    { SLNO: '15', status: 'Warning', PlantName: 'KP Plan of Oil Refinery' ,Name:"Rajan"},
    { SLNO: '16', status: 'unsafe', PlantName: 'Third Manufacturing Division' ,Name:"Vishnu"},
]